# After changing this file, verify the syntax on http://lint.travis-ci.org/
language:
    - cpp
    - python
python:
    - "2.7"
compiler:
    - gcc
sudo: required
dist: trusty
install: ./scripts/install_test_dependencies.sh
before_script: 
    - source /opt/ros/jade/setup.bash
    - ./scripts/setup.sh ~/tmp_workspace
script: ./scripts/run_tests.sh
