# After changing this file, verify the syntax on http://lint.travis-ci.org/
language:
    - cpp
    - python
python:
    - "2.7"
compiler:
    - gcc
sudo: required
dist: trusty
install:
    - pwd
    - ./lidapy-framework/scripts/install_test_dependencies.sh
before_script: source ./lidapy-framework/scripts/setup_test.bash
script: ./lidapy-framework/scripts/run_tests.sh